# This Github Actions runs when a Code is pushed to any branch as well as when a pull request is merged.
name: Code Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testing/coverage_tests
      - testing/README-A
  pull_request:
    types:
      - closed


jobs:
  code_coverage:
  # if_merged_or_pushed:
  #   if: ${{ (github.event.pull_request.merged == true) || (github.event.push == true) }}
  # code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install CI
        run: |
          npm ci
          npm run test | tee unit-tests.txt
          npm run coverage | tee coverage.txt

      - name: README Creation
        shell: bash
        run: |
          set -x
          github_refname="${{ github.ref_name }}"
          github_sha="${{ github.sha }}"
          sed -e '/<!-- Unit Tests Start -->/,/<!-- Unit Tests End -->/{/^<!--.*-->/!d}' \
              -e '/<!-- Unit Tests Start -->.*$/r unit-tests.txt' \
              -e '/<!-- Code Coverage Start -->/,/<!-- Code Coverage End -->/{/^<!--.*-->/!d}' \
              -e '/<!-- Code Coverage Start -->.*$/r ./coverage.txt' \
               ./README.md >./README.md.bak \
          && sed -i -e 's/^Branch:*,/Branch: '"${github_refname/\//\\/}"',/g' README.md.bak \
          && sed -i -e 's/Commit SHA: #.*$/Commit SHA: #'"${github_sha:0:7}"'/g' README.md.bak
          mv README.md.bak README.md

      - name: Commit and Push
        run: |
          git config --local user.name "readme-updater"
          git add README.md
          git commit -m "Updated README.md"
          git push

      # - name: Codecov
      #   uses: codecov/codecov-action@v3.1.0
      #   with:
      #     # token: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true
