# This Github Actions runs when a Code is pushed to any branch as well as when a pull request is merged.
name: TAP Code Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - testing/tap-tests
  pull_request:
    types:
      - closed


jobs:
  code_coverage:
  # if_merged_or_pushed:
  #   if: ${{ (github.event.pull_request.merged == true) || (github.event.push == true) }}
  # code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install CI
        run: |
          npm ci
          npm run tap-test
          npm run tap-coverage

      - name: Add docs/coverage to git
        run: |
          git config --local user.name "Documentation-Bot"
          git add docs/*
          git commit -m "Adding Docs"
          git push

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     junit_files: "docs/jest-unittest/jest-junit-reports/jest-junit-reports.xml"

      # - name: Conclusion
      #   run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
